export default function handler(req: any, res: any) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  const authHeader = req.headers.authorization || '';
  const token = authHeader.startsWith('Bearer ') ? authHeader.substring(7) : '';

  if (!token) {
    return res.status(401).json({ authenticated: false, error: 'Token ausente' });
  }

  // Tokens generated by login handler
  return res.status(200).json({
    authenticated: true,
    message: 'Sessão ativa',
  });
}
